### ISSUE TITLE
position() does not return the center of rotation

### ISSUE THREAD

**Issue by lestofante** [rlane/oort3#45]
if the ship is not moving, but only rotating, the position() is changing

the difference is +-2 unit in each axis

```rust
use oort_api::prelude::*;

pub struct Ship {
    last_position: Vec2,
}

impl Ship {
    pub fn new() -> Ship {
        Ship {
            last_position: vec2(0.0, 0.0),
        }
    }

    pub fn tick(&mut self) {
        // position will change,but we are only turning!
        debug!("position {0}", position());
        turn(1000.0);
        if self.last_position != vec2(0.0, 0.0){
            draw_line(position(), self.last_position, 255);
        }
        if current_tick() % 100 == 0{
            self.last_position = position();
        }
    }
}
```

**Comment by rlane** [comment]
@TheLostLambda That's great! I had some work in progress that I cleaned up and pushed to the center-of-mass branch. The remaining problem is that the tutorial_squadron reference solution doesn't pass. We need to tweak it to make it more reliable but still be very simple and not spoil problems for players unnecessarily.

This is made harder by the fact that all 10 verification seeds actually do complete successfully when run in the web UI, so there's some discrepancy in the simulation. Seed 4 is where the non-browser simulation fails. We can see in the web UI that the reference solution doesn't do a great job on this one (even if it wins), so improving that could be enough.

ps. After editing a built-in AI (like tutorial_squadron.solution.rs) run `cargo oort-rebuild-ai` so that your changes get picked up by the test suite.

**Comment by TheLostLambda** [comment]
Hi @rlane ! Thanks for all of the information! I'll try to fix things up tomorrow! Now is probably the wrong time to admit I haven't done that tutorial yet :sweat_smile: , but I'm certainly up for the challenge!

I'll let you know how I get on!
